Api Key - Add a variant message when an index uid format is invalid for the `indexes` field.
meilisearch/specifications pull request #113
Opened 2022-02-15 12:34 UTC by gmourier

Use the `invalid_index_uid` error message as a variant for `invalid_api_key_indexes` error when an invalid index uid is set into the `indexes` field

### Related issue

https://github.com/meilisearch/meilisearch/issues/2158

2022-02-15 13:54 UTC, curquiza requested changes

2022-02-15 14:09 UTC, gmourier commented on text/0085-api-keys.md
> +- 🔴 Sending a value that is not a valid `index` (e.g. regarding the index uid format) in the `indexes` field returns an [invalid_index_uid](0061-error-format-and-definitions.md#invalid_index_uid) err
Total miss from my side! Thanks!

2022-02-15 14:13 UTC, curquiza commented on text/0085-api-keys.md
> +
```suggestion
```

2022-02-15 14:13 UTC, curquiza approved these changes

2022-02-15 14:19 UTC, curquiza submitted a review, later dismissed

2022-03-24 13:32 UTC, curquiza submitted a review, later dismissed

2022-10-18 11:52 UTC, closed without merging