Documents API
meilisearch/specifications pull request #133
Opened 2022-03-21 16:41 UTC by gmourier

2022-03-23 13:49 UTC, gmourier commented
test

2022-03-28 13:46 UTC, ManyTheFish requested changes

2022-03-28 13:46 UTC, ManyTheFish commented on text/0124-documents-api.md
> +- 🔴 Sending a value with a different type than `String` or `null` for `attributesToRetrieve` will return a [bad_request](0061-error-format-and-definitions.md#bad_request) error.
```suggestion
- 🔴 Sending a value with a different type than an array of `String` or `null` for `attributesToRetrieve` will return a [bad_request](0061-error-format-and-definitions.md#bad_request) error.
```
I don't know if you want to precise it.

2022-03-28 13:46 UTC, ManyTheFish commented on text/0124-documents-api.md
> +If an already existing document (same identifier) is set, the old document will be only partially updated according to the fields of the new document. Thus, any fields not present in the new document
```suggestion
If an already existing document (same identifier) is set, the old document will be only partially updated according to the fields of the new document. Thus, any fields not present in the new document are kept and remain unchanged.
```

2022-03-28 13:46 UTC, ManyTheFish commented on text/0124-documents-api.md
> +To completely overwrite a document, see [3.1.3. `POST` - `indexes/:index_uid/documents`](#313-post---indexesindexuiddocuments) section.
I don't know if it's relevant to keep this in a spec, for me, it's more a documentation thing.

2022-03-28 13:47 UTC, ManyTheFish commented on text/0124-documents-api.md
> +- 🔴 Sending a value with a different type than `String` or `null` for `attributesToRetrieve` will return a [bad_request](0061-error-format-and-definitions.md#bad_request) error.
but if you want to precise it, I probably miss equivalent error definitions

2022-03-28 13:48 UTC, ManyTheFish commented on text/0124-documents-api.md
> +To completely overwrite a document, see [3.1.3. `POST` - `indexes/:index_uid/documents`](#313-post---indexesindexuiddocuments) section.
I don't know if it's relevant to keep this in a spec, for me, it's more a documentation thing.

2022-03-29 15:20 UTC, gmourier commented
Thanks @ManyTheFish !

2022-03-30 12:46 UTC, merged