Tasks API - Rename `uid` to `taskUid` in the `202 - Accepted` Summarized Task Response
meilisearch/specifications pull request #144
Opened 2022-04-21 10:03 UTC by gmourier

2022-04-21 11:43 UTC, curquiza approved these changes
🚀

2022-04-21 11:53 UTC, gmourier commented
🚨  @gmourier These changes should also be included for the [dump API](https://github.com/meilisearch/specifications/pull/139) since the response to a dump creation becomes a 202 Accepted.

2022-05-16 13:26 UTC, bidoubiwa requested changes
🔥🔥🔥🔥

2022-05-16 13:26 UTC, bidoubiwa commented on text/0060-tasks-api.md
> +| taskUid    | integer | Unique sequential identifier           |
```suggestion
| taskUid    | integer | Unique sequential identifier |
```

2022-05-17 13:57 UTC, merged