API Keys - Introduces a `uid` field  to make API Key determinists and a `name` field to ease information reading.
meilisearch/specifications pull request #148
Opened 2022-05-04 09:58 UTC by gmourier

🤖  [API Diff]() _Put the link of the GitHub comment generated by bump.sh; Apply the `OpenApi` label_
📄 [Rendered]() _Put the link of the rendered markdown file_

---

# Summary

This update to the Keys API makes several changes:

- It is possible to create deterministic a `key` value by specifying a `uid` field at creation.
- Adds a `name` field to give a human-readable name if needed to make the keys more readable in a list.
- The master key is only dedicated to key management, it can't be used for other endpoints. Making Meilisearch more secure by design and thus preventing users from introducing a security vulnerability.
- Updating a key only allows the `name` and `description` fields.

---

# Changes

## `uid` Field Addition

The generation of a randomized prefix of 8 characters is suppressed by the existence of the `uid` field. This field accepts a string representing a UUID v4.

It is possible to specify this `uid` field when creating a key, if not specified it is generated by Meilisearch. 

As the value of `key` is a hash of the `uid` and the master key, it is possible to have deterministic `key` values between instances sharing the same configuration thus keeping some interesting security features as: 

- If the master key changes, all `key` values are automatically changed.
- The API key resources are propagated into the dumps and snapshot without displaying the `key` field in clear.

A key is retrieved from its `uid` rather than its `key` value. e.g. `GET /keys/:uid` instead of `GET /keys/:key`.

## `name` Field Addition

A `name` field is added to allow a human-readable name to better read the information within a list of keys. The `description` field is kept to add additional information if needed.

For example, the `description` field is useful to give important information about the keys generated by default that would not necessarily have its place in the `name`. This makes it easier to parse in a dashboard when building a UI or in the `GET /keys` response.

The default generated API keys are updated to reflect this change. 

```json
{
    ...,
    "name": "Default Admin API Key",
    "description": "(Use it for all other than search operations. Caution! Do not expose it on a public frontend)",
    ...
}
```

## Master key

The master key can only be used to manage API keys.

It has been found several times that users use the master key to make client-side requests, which is problematic for their security. In order to ensure that they do not inadvertently put themselves in danger, the master key can no longer access routes other than `/keys`.

## API Key Update

It is no longer possible to update the sensitive information of an API key which could introduce security problems as side effects.

It is however possible to update the `name` and `description` fields.

# Out Of Scope

Adding a unique human-readable field as an `alias` to retrieve an API Key other than its `uid` is not considered in this iteration. It should be easy to add it later without breaking changes.

---

# Attention To Reviewers

@meilisearch/cloud-team We basically need your attention on all these changes. 

The big question mark could be the update of the permissions of an API key on your side which could be requested by users. This could be done within a transaction on your side to still allow the update if it is a vital need. 

The workaround would be to delete the key that needs to be updated and recreate one with the new permissions by giving it the `uid` of the previous one.

Also, concerning the master key which is now restricted to endpoint `/keys` access only, do you have any particular constraints?

@nicolasvienot The addition of the `name` field should allow you to have more fluidity in the construction of a UI and thus avoid having to parse the `description` field.

---

## Misc

- [] Update OpenAPI specification file

2022-05-04 18:09 UTC, brunoocasali reviewed
Awesome work @gmourier 💪

2022-05-13 09:38 UTC, gmourier commented on text/0085-api-keys.md
> +- Add rfc2822 format expression for `expiredAt` field. e.g. `Wed, 18 Feb 2022 23:16:09 GMT`
This is just to be able to support more formats and make it easier to handle. It shouldn't be that specific; just say, "Support more formats."

2022-05-23 13:08 UTC, gmourier commented on open-api.yaml
> +          description: A uuid v4 to identify the API Key. If not specified, it's generated by Meilisearch.
Yes, I've just added the error messages in the dedicated specification 😇

2022-05-23 13:09 UTC, gmourier commented on text/0085-api-keys.md
> +- API key resources are propagated to snapshots and dumps.
"`name` and `description` fields are the only editable fields of an API key." was already here!

2022-05-23 13:11 UTC, gmourier commented on text/0085-api-keys.md
> +    "description": "(Use it to search from the frontend)",
Yes! Thanks @brunoocasali !

2022-05-23 13:39 UTC, gmourier commented
@meilisearch/integration-team There remains a design question regarding the JWT payload for tenant token.

Currently, the JWT requires an `apiKeyPrefix`. It should be renamed since the prefix won't exist anymore. Here is 2 possibility:

- `apiKey`: Fill in the signing API key's full `key` field.
- `apiKeyUid`: Fill in the `uid` for the signing API key.

What will be the best choice according to you?

2022-05-23 13:44 UTC, gmourier commented
@ManyTheFish will explore two additional if the time permits it. Otherwise it will be considered in the future.

## GET an API Key helper

See if it's possible to have `GET /keys/:uid_or_key` to transparently get the details of an API Key given the field given (`uid` or `key`). If added in the future, it's not a breaking change.

## Add keys management rights

Since the `master-key` will only be used to manage `/keys`. We will explore if we can easily add new rights to manage `keys`. This way, the master-key will be less shared and specific keys could be create to manage the `keys`.

2022-05-31 13:22 UTC, ManyTheFish requested changes

2022-05-31 13:22 UTC, ManyTheFish commented on text/0061-error-format-and-definitions.md
> +    "message": "`uid` field value `:value` is invalid. It should be a valid uuidv4 string or ommited.",
related to https://github.com/meilisearch/meilisearch/pull/2438#discussion_r885546155

```suggestion
    "message": "`uid` field value `:value` is invalid. It should be a valid UUID v4 string or omitted.",
```

2022-05-31 13:22 UTC, ManyTheFish commented on text/0061-error-format-and-definitions.md
> +    "message": "`uid` field value `:value` already exists for an API key.",
related to https://github.com/meilisearch/meilisearch/pull/2438#discussion_r885547329

```suggestion
    "message": "`uid` field value `:value` is already an existing API key.",
```

2022-06-01 10:29 UTC, gmourier commented
📡

@meilisearch/cloud-team The change about the master key has been discarded. See https://github.com/meilisearch/product/discussions/443#discussioncomment-2862683

@meilisearch/core-team @meilisearch/docs-team @meilisearch/integration-team

- The specification is up-to-date to mention the last successful exploration point made last week.
    - New `actions` are introduced to the management of the API Keys resource. `keys.get`, `keys.create`, `keys.update`, `keys.delete`.
    - `GET` - `/keys/:key` is now `/keys/:uid_or_key`. An API Key can now be fetched by its `uid` or its `key` field value.
    - The tenant token claim `apiKeyPrefix` is renamed `apiKeyUid` and must be given the signing API Key `uid` field value.

2022-06-01 11:49 UTC, ManyTheFish requested changes

2022-06-01 12:03 UTC, gmourier commented on text/0061-error-format-and-definitions.md
> +}
Good idea @ManyTheFish! Shouldn't it in this order? e.g. "`:fieldname` field cannot..."

2022-06-01 14:35 UTC, gmourier commented on text/0061-error-format-and-definitions.md
> +}
Updated!

2022-06-13 11:22 UTC, ManyTheFish requested changes
@gmourier, I suggested changes about key derivation.

2022-06-13 11:22 UTC, ManyTheFish commented on text/0085-api-keys.md
> +The final key is then an SHA-256 hash made of the `uid` and the master key concatenation.
```suggestion
The final key is then an HMAC with the master key, pre-hashed by an SHA-256 algorithm, as the secret and the `uid` as the data. HMAC uses an SHA-256 algorithm internally.
```

2022-06-13 11:22 UTC, ManyTheFish commented on text/0085-api-keys.md
> +`SHA-256(:uid, :master-key)` gives the final `key` field to use when authorizing requests.
```suggestion
`HMAC(secret: SHA-256(:master-key), data: :uid)` gives the final `key` field to use when authorizing requests.
```

2022-06-13 11:22 UTC, ManyTheFish commented on open-api.yaml
> +          description: The derived key to use in the Authorization header to authorize requests. Generated by Meilisearch with a SHA-256 hash of the uid and the master key.
```suggestion
          description: The derived key to use in the Authorization header to authorize requests. Generated by Meilisearch with an HMAC, using an SHA-256 hash, of the uid and the master key.
```

2022-07-05 15:00 UTC, ManyTheFish requested changes
Request changes related to https://github.com/meilisearch/meilisearch/pull/2584

2022-07-07 13:55 UTC, merged