Write a specification for the new (and old) search filters
meilisearch/specifications pull request #163
Opened 2022-07-20 17:43 UTC by loiclec

With the release of Meilisearch v0.29.0, we hope to add more filter operators and to change the behaviour of `NOT` and `!=`. This PR updates the specification so that it is up-to-date with these changes. I have also updated it to be more precise and complete. 

I am not entirely sure what the expected style of the spec is supposed to be, so please let me know if something can be slightly improved or if it is completely wrong :)

2022-08-09 11:28 UTC, gmourier reviewed
This is super clear @loiclec! Thanks

2022-08-10 10:30 UTC, irevoire requested changes
Awesome, you documented so many edge cases!

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.1 Grammar
```suggestion
###### 3.1.2.1.1 Grammar
```

1.2.3.4.5 is supposed to have 6 # from what I see

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.2 Naming a filterable attribute
```suggestion
###### 3.1.2.1.2 Naming a filterable attribute
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.5 Equality
```suggestion
###### 3.1.2.1.5 Equality
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.6 Inequality
```suggestion
###### 3.1.2.1.6 Inequality
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +Furthermore, there is no way to write a filter to select documents which contain a value that is different than a given string or number. In the example above, `size != 1` did not select the document
Nice I never thought of that

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.7 Comparison
```suggestion
###### 3.1.2.1.7 Comparison
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +Multiple filters can be combined together using the operators `AND` and `OR`. These infix operators take two sub-filters as arguments
```suggestion
Multiple filters can be combined together using the operators `AND` and `OR`. These infix operators take two sub-filters as arguments.
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.9 Negating a filter
```suggestion
###### 3.1.2.1.9 Negating a filter
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.10 Exists
```suggestion
###### 3.1.2.1.10 Exists
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.11 In
```suggestion
###### 3.1.2.1.11 In
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +##### 3.1.2.1.12 Geo Search
```suggestion
###### 3.1.2.1.12 Geo Search
```

2022-08-10 10:30 UTC, irevoire commented on text/0118-search-api.md
> +#### 3.1.2.2. Array Syntax
```suggestion
##### 3.1.2.2. Array Syntax
```

2022-10-03 11:57 UTC, irevoire approved these changes
nice

2022-10-03 11:59 UTC, gmourier approved these changes

2022-10-03 12:15 UTC, gmourier commented
Thank you @loiclec !

2022-10-03 14:41 UTC, merged