Merge snapshot options
meilisearch/specifications pull request #214
Opened 2023-01-05 10:58 UTC by dureuill

No API change

---

# Summary

The `--schedule-snapshot` and `--snapshot-interval-sec` options were merged in https://github.com/meilisearch/meilisearch/issues/3131

---

# Changes

- Remove any mention of `--snapshot-interval-sec`
- Propagate changes to telemetry
- Change specification of `--schedule-snapshot` to reflect its new behavior

# Out Of Scope

N/A 

---

# Attention To Reviewers

`--schedule-snapshot` is the first option that is "tri-valued" (absent/flag only/flag with a value). I tried to be clear but the wording should be reviewed carefully

---

## Misc

- [] Update OpenAPI specification file _(if needed; Apply the `OpenApi` label)_
- [] Update telemetry datapoints _(if needed; Apply the `Telemetry` label)_

2023-01-05 12:34 UTC, gmourier requested changes
I've asked for a review from @maryamsulemani97 regarding the technical explanations of the "tri-valued" concept you explaining lines 285-287. It seems good to me.

2023-01-05 12:34 UTC, gmourier commented on text/0119-instance-options.md
> +#### 3.3.16. Ignore missing snapshot
```suggestion
#### 3.3.17. Ignore missing snapshot
```

2023-01-05 12:44 UTC, maryamsulemani97 approved these changes
LGTM! 🤖

2023-01-11 08:50 UTC, gmourier commented on text/0119-instance-options.md
> +#### 3.3.16. Ignore missing snapshot
```suggestion
#### 3.3.17. Ignore missing snapshot
```

2023-02-06 10:36 UTC, merged