Document the latest metrics improvements
meilisearch/specifications pull request #242
Opened 2023-05-30 13:02 UTC by irevoire

🤖  [API Diff]() _Put the link of the GitHub comment generated by bump.sh if generated; Apply the `OpenApi` label_

---

# Summary

Implemented in https://github.com/meilisearch/meilisearch/pull/3789

- Prefix all the metrics by `meilisearch` so they're easier to find
- Add the real database size used by meilisearch
- Add metrics on the task queue

2023-05-31 12:13 UTC, gmourier requested changes
Thanks @irevoire 🚂

2023-05-31 12:13 UTC, gmourier commented on text/0174-metrics-api.md
>  http_requests_total{method=":httpMethod",path=":resourcePath"} :numberOfRequest
```suggestion
meilisearch_http_requests_total{method=":httpMethod",path=":resourcePath"} :numberOfRequest
```

2023-05-31 12:13 UTC, gmourier commented on text/0174-metrics-api.md
>  http_response_time_seconds_count{method=":httpMethod",path=":resourcePath"} :numberOfRequest
```suggestion
meilisearch_http_response_time_seconds_count{method=":httpMethod",path=":resourcePath"} :numberOfRequest
```

2023-05-31 12:13 UTC, gmourier commented on text/0174-metrics-api.md
>  Returns the size of the database in bytes.
Could we add some precision for that one? Saying it represents the memory-mapped space "taken" by LMDB is okay to me!

2023-05-31 15:11 UTC, irevoire commented on text/0174-metrics-api.md
>  http_requests_total{method=":httpMethod",path=":resourcePath"} :numberOfRequest
Oops thanks

2023-05-31 15:44 UTC, gmourier reviewed
@irevoire I just realized we have a `sampleResponse` field listing _some_ metrics values under the Open API /metrics endpoint; we could either remove that sample response or update the example by including the `meilisearch_` prefix. It's up to you!

2023-05-31 21:08 UTC, 94noni commented on text/0174-metrics-api.md
> +Returns the total number of index for the Meilisearch instance.
hey, small typo found passing by reading more on meilisearch specs repo
seems a copy past of the above metric name desc

2023-06-01 10:14 UTC, macraig approved these changes

2023-06-05 10:54 UTC, gmourier commented on open-api.yaml
> +                  http_response_time_seconds_bucket{method="GET",path="/metrics",le="0"} 0
```suggestion
                  meilisearch_http_response_time_seconds_bucket{method="GET",path="/metrics",le="0"} 0
```

2023-06-05 10:56 UTC, gmourier requested changes
Should it be prefixed by `meilisearch` on every metrics?

2023-07-31 10:28 UTC, gmourier approved these changes

2023-07-31 10:28 UTC, merged