Paginated Search
meilisearch/specifications pull request #42
Opened 2021-05-25 10:19 UTC by gmourier

Initialize specification for finite pagination on the search API endpoint.

2021-05-25 13:49 UTC, bidoubiwa requested changes

2021-05-25 14:07 UTC, gmourier commented on text/0042-paginated-search.md
> +Naturally, our users rely on `nbHits` to determine the number of possible pages. However, in the context of the search endpoint and the internal functioning of the engine dedicated to a fast and accu
Nice catch @bidoubiwa !

2021-05-31 06:51 UTC, qdequele approved these changes

2021-05-31 16:05 UTC, bidoubiwa approved these changes

2021-05-31 16:52 UTC, MarinPostma approved these changes
lgtm, thanks :)

2021-06-01 06:40 UTC, merged